### ISSUE TITLE
Fatal error when using createCard()

### ISSUE THREAD

**Issue by adamjgriffith** [dioscouri/omnipay-cybersource#25]
```
Fatal error: Uncaught Error: Call to undefined method Omnipay\Cybersource\Message\CreateCardRequest::getCardData() in /vendor/dioscouri/omnipay-cybersource/src/Message/CreateCardRequest.php:18
Stack trace:
#0 /vendor/omnipay/common/src/Common/Message/AbstractRequest.php(732): Omnipay\Cybersource\Message\CreateCardRequest->getData()
#1 /CreateCard.php(95): Omnipay\Common\Message\AbstractRequest->send()
```

```
try {
    $gateway = Omnipay::create('Cybersource');

    $gateway->setProfileId('REDACTED');
    $gateway->setAccessKey('REDACTED');
    $gateway->setSecretKey('REDACTED');
    $gateway->setCurrency('GBP');

    if (isDevelopment()) {
        $gateway->setTestMode(TRUE);
    }

    $options = array(
        'firstName' => 'John',
        'lastName' => 'Doe',
        'number' => '4111111111111111',
        'expiryMonth' => '12',
        'expiryYear' => '2022',
        ...
    );

    $request = $gateway->createCard($options);

    $response = $request->send();

    if ($response->isSuccessful()) {

    } elseif ($response->isRedirect()) {
        $response->redirect();
    } else {
        exit($response->getMessage());
    }
} catch ($e) {
    exit('Sorry, there was an error processing your payment. Please try again later.');
}
```

**Comment by adriangordon1231** [comment]
Following the strack-trace, the "send" function triggers a "getCardData" function which in turn triggers a function that has not actually been implemented in the library called "getData".  This library does not seem to support tokenization.
